### ISSUE TITLE
Download speed throttle

### ISSUE THREAD

**Issue by shakyShane** [BrowserSync/UI#11]
To go along with the latency throttler - if we can figure out how to throttle the responses for both server + proxy, then we can offer a chrome dev-tools style list of pre-defined speeds such as 

![throttle](http://cl.ly/image/43303F170e06/Screen%20Shot%202015-02-17%20at%2015.24.36.png)

**Comment by RootMale** [comment]
+1. I already saw thelatency in the ui. Maybe it solves the trick? However this stuff should be configured programmatically also.

**Comment by shakyShane** [comment]
I have this ready, it will be in the next release.

The `latency` throttle in the current ui is just that, a latency throttle - it delays the response time, but when that delay is up, you get all the data at full speed. in the new version the latency is still throttled but we also throttle the download/upload speeds too just like chrome dev tools so it's much better :)

**Comment by shakyShane** [comment]
Landed in `2.5`

**Comment by fmartins** [comment]
Anyone knows if is possible to configure the Network Throttle by API?
I looked at < https://www.browsersync.io/docs/options > and does not found nothing about... 

This is a sample of my config in _gulpfile.js_.

```
  browserSync({
    server: {
      baseDir: './'
    },
    // TODO Configure network throttle.
    port: 3000,
    ui: {
      port: 3001
    },
    open: false,
    online: false,
    notify: false,
  });
```

**Comment by hirnschmalz** [comment]
API configuration would be great. Is it possible? I also couldn't find any hints on that in the docs.
