### ISSUE TITLE
Feature Request: QR Code For External URL

### ISSUE THREAD

**Issue by crswll** [BrowserSync/UI#32]
I was trying to think of a way to get browser-sync to wake up all my devices and go straight to a URL. That was way more work then I'm ready for so I dialed it back. 

I was thinking of a way to avoid typing in the address. I'm wondering if there's a way we can get a QR code into UI (in the external section of overview) or maybe even a command line option that'll output one right to the console (something like: https://www.npmjs.com/package/qrcode-terminal) .

Anyway. I'd definitely love to give it a shot if you think it's something you'd be willing to go with.

**Comment by aminalhazwani** [comment]
+1

**Comment by mucsi96** [comment]
+1

**Comment by achjaderleon** [comment]
+1

**Comment by SimonFricker** [comment]
+1

**Comment by quisse** [comment]
+1

**Comment by quisse** [comment]
https://github.com/stephenfri/bs-console-qrcode
