### ISSUE TITLE
Nothing listed under "Current Connections"

### ISSUE THREAD

**Issue by glen-84** [BrowserSync/UI#37]
I'm using snippet mode, and I have two browsers connected. When I hit `RELOAD ALL` (for example), it works correctly, but there is nothing listed under "Current Connections". Am I missing something?

    Browsersync [ 2.12.5 ]
    Node [ 5.11.0 ]
    Npm [ 3.8.6 ]

Win10

**Comment by gotascii** [comment]
I am also having a similar issue. Reload All works, however, there are no entries listed under "Current Connections". I am using lite-server with a basic server config. Using:

Browsersync [ 2.12.8 ]
Node [ 6.0.0 ]
Npm [ 3.8.6 ]

**Comment by Muzietto** [comment]
Same as above, using:
- win 7
- browsersync 2.13.0
- node 4.4.7
- npm 3.5.3

**Comment by bechtold** [comment]
I use it as a gulp plugin, reload all and injecting css etc. works fine.
But I have the same problem, not seeing the connected devices.
I use the following setup:
```
OS X 10.10.5
node 4.2.1
npm 2.14.7
browsersync 2.14.0
```

I updated now (via homebrew) to:
```
node 6.3.1
npm 3.10.3
```

Still not working.

**Comment by blowsie** [comment]
I also have the same issue, all other functionality is working just fine, but current connections is empty

**Comment by etsrepo** [comment]
I also have the same issue, all other functionality is working just fine, but current connections is not working

```
Ubuntu 16.04
node v6.3.1
npm 3.10.3
browsersync 2.14.0
```

**Comment by eriktoyra** [comment]
I experience the same thing. BrowserSync.io synchronizes the clients as expected but no connections shows up under _Current Connections_.

```
OSX 10.11.5
node v.5.4.0
npm 3.3.12
browsersync 2.2.0
```

**Comment by marcolindner** [comment]
Same here:

`Windows 7
node 4.4.5
npm 2.1.5
browsersync 2.15.0`

**Comment by manu09** [comment]
I still have this issue. There are no browsers listed in current connections.

**Comment by trompx** [comment]
Same problem
Ubuntu 14.04
npm 3.10.2
node 5.9.1
browsersync 2.2.0

**Comment by blowsie** [comment]
@trompx you are using an old version that did not include the fix

**Comment by trompx** [comment]
@blowsie my bad, that was my grunt-browser-sync version which uses v2.14.0 of browsersync. I am stuck with grunt atm, so I will see if the maintainer of the repo is willing to upgrade the version.

**Comment by patricknelson** [comment]
I have a similar issue, using:

- `browser-sync@2.24.1` (latest)
- `grunt-browser-sync@2.2.0` (latest, but a year old at this point)
- `npm 3.10.10`
- node v6.11.4
- Windows 10

Not sure what changed. It was working, now sadly it is not. The symptoms I have now are:

- Does say say "Browsersync: connected" in the corner
- Will no longer inject CSS changes
- Nothing at all in the console log on the page
- UI: Current connections area is empty
- UI: History is empty 

**However**, oddly enough, it *will* refresh the page whenever other files change (e.g. html). I'm a fairly new user and pretty baffled about what could cause it to suddenly stop working 😞

**Comment by shakyShane** [comment]
@patricknelson there was a fairly big rewrite of the client-side code for 2.24.0 - it seems like a bug may have surfaced - I'm looking into it

**Comment by patricknelson** [comment]
Ok thanks @shakyShane - it may be worth noting that I did attempt to install an older version of `browser-sync`, ~roughly~ exactly `2.23.7` (FIXED), and it seemed to have the same effect as long as I was using `grunt`. I’m not at a computer at the moment so I can’t find the exact version, but it didn’t affect the  version reported by the UI web interface, which was still at the latest version of `2.24.1`. Interestingly, everything did seem to work as expected when I launched a separate CLI (from the global install of `browser-sync`) and I recall it working normally (ran that one first, of course, so it could bind to `:3000` before `grunt`’s version of `browser-sync`)

The best I could deduce from that was maybe it had to do with some combination of how it integrated with `grunt-browser-sync` but I have absolutely no clue at all. I resigned myself to defeat and decided that if I couldn’t figure it out tomorrow that I’d just resort to limping along with `watch` until it’s fixed or I can move our massive `Gruntfile.js` over to `gulp`!

**EDIT:** Updated local `browser-sync` version.

**Comment by patricknelson** [comment]
Ok, I fixed my issue by reverting to an older version. I found the exact version of local `browser-sync` installed: `2.23.7`.

I was confused initially but forgot that `browser-sync` was being installed under `grunt-browser-sync` (not at the root level duh, /facepalm). Everything is totally fixed for me after shrink wrapping it, or with `yarn`:

```json
  "resolutions": {
    "grunt-browser-sync/**/browser-sync": "~2.23.0"
  }
```
