### ISSUE TITLE
hbs files not building

### ISSUE THREAD

**Issue by nitinsurana** [BrowserSync/UI#50]
1. cb build-all doesn't build the .hbs files
2. cb watch throw error saying "crossbow.stream is not a function"
3. gulp crossbow doesn't work, cause there's no crossbow task in gulpfile.js

**Comment by lalaemls** [comment]
@nitinsurana  hi! is the problem solved?

**Comment by lalaemls** [comment]
@shakyShane I can't find the stream function on crossbow object
how can i build it?

**Comment by nitinsurana** [comment]
@lalaemls I don't work on it anymore and unable to recall if I was able to solve it then, sorry!

**Comment by shakyShane** [comment]
Hi all - Sorry but this repo is no-longer in use - it's been moved to https://github.com/BrowserSync/browser-sync (under packages)
