### ISSUE TITLE
UI not working with https:true

### ISSUE THREAD

**Issue by fyyyyy** [BrowserSync/UI#54]
v 2.18.13

With the snippet mode, the UI page still tries to connect to browser-sync via http instead of https.
http://localhost:3000/browser-sync/socket.io/?EIO=3&transport=polling&t=L_VVT8U
The UI page is also running on http://localhost:3001 instead of https

```
//config

		browserSync: {

			options: {
				https: true,
				socket: {
					domain: 'localhost:3000'
				}
			}
               }

**Comment by klip** [comment]
UI will always work on http

But if you have decided to specify socket option you do need to add https

browserSync: {

			options: {
				https: true,
				socket: {
					domain: 'https://localhost:3000'
				}
			}
               }
BTW in your example you really don't need to specify socket option, it points to default anyway

**Comment by fyyyyy** [comment]
Thanks, that fixed it :)

I can confirm it also works like that

	options: {
			https: true
		}
